apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  postgres-password: "bankpassword123" # كلمة سر قاعدة البيانات
  jwt-secret: "my-super-secure-devops-key" # مفتاح التوقيع للـ API